version: "3" # can be adapapted if necessary

services:
    heimdall:
      image: linuxserver/heimdall
      container_name: heimdall
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Shanghai
      volumes:
        - /path/to/appdata/config:/config
      ports:
        - 8087:80
        - 443:443
      restart: unless-stopped
  

    emby:
      image: linuxserver/emby
      container_name: emby
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Shanghai
        - UMASK_SET=022 #optional
      volumes:
        - /home/pi/library:/config
        - /home/pi/tvshows:/data/tvshows
        - /home/pi/movies:/data/movies
      ports:
        - 8096:8096
        - 8920:8920 #optional
          #devices:
              # - /home/pi/emby-share:/dev/dri
      restart: unless-stopped
